-- ============================================================================
-- RISK: Kamino Sensitivity Analysis Filtered by Asset
-- ============================================================================
-- IMPLEMENTED: See pfx/dbsql/functions/kamino/get_view_klend_sensitivities_by_asset.sql
--
-- This is now an 8-parameter overload of get_view_klend_sensitivities that adds
-- p_coll_assets TEXT[] and p_lend_assets TEXT[]. The overload resolves symbols
-- to reserve addresses via aux_market_reserve_tokens and filters obligation_base
-- using the && (array overlap) operator on deposit_reserve_by_asset and
-- borrow_reserve_by_asset. NULL arrays mean "all assets" (no filter), making
-- it backward-compatible with existing 6-parameter calls to the base function.
-- ============================================================================
