-- get_view_dex_last: Direct read from mat_dex_last
-- Same signature and output schema as the original (dexes/dbsql/views/get_view_dex_last.sql)
-- but reads from the pre-computed snapshot table instead of scanning multiple source tables.

DROP FUNCTION IF EXISTS dexes.get_view_dex_last(TEXT, TEXT, INTERVAL) CASCADE;
CREATE OR REPLACE FUNCTION dexes.get_view_dex_last(
    protocol_param TEXT,
    pair_param TEXT,
    lookback_param INTERVAL
)
RETURNS TABLE (
    pool_address TEXT,
    protocol TEXT,
    token_pair TEXT,
    symbols_t0_t1 TEXT[],
    liq_query_id BIGINT,
    price_t1_per_t0 NUMERIC,
    impact_t0_quantities DOUBLE PRECISION[],
    impact_from_t0_sell1_bps NUMERIC,
    impact_from_t0_sell2_bps NUMERIC,
    impact_from_t0_sell3_bps NUMERIC,
    t0_reserve BIGINT,
    t1_reserve BIGINT,
    tvl_in_t1_units BIGINT,
    reserve_t0_t1_millions NUMERIC[],
    reserve_t0_t1_balance_pct NUMERIC[],
    swap_count_period BIGINT,
    lp_in_count_period BIGINT,
    lp_out_count_period BIGINT,
    swap_vol_in_t1_units BIGINT,
    swap_vol_in_t0_units BIGINT,
    swap_vol_in_t1_units_pct_reserve NUMERIC,
    swap_vol_in_t0_units_pct_reserve NUMERIC,
    swap_vol_out_t1_units BIGINT,
    swap_vol_out_t0_units BIGINT,
    swap_vol_out_t1_units_pct_reserve NUMERIC,
    swap_vol_out_t0_units_pct_reserve NUMERIC,
    swap_vol_period_t0_in BIGINT,
    swap_vol_period_t0_out BIGINT,
    swap_vol_period_t1_in BIGINT,
    swap_vol_period_t1_out BIGINT,
    lp_token0_in_period_sum BIGINT,
    lp_token0_out_period_sum BIGINT,
    lp_token1_in_period_sum BIGINT,
    lp_token1_out_period_sum BIGINT,
    lp_token0_in_period_sum_pct_reserve NUMERIC,
    lp_token0_out_period_sum_pct_reserve NUMERIC,
    lp_token1_in_period_sum_pct_reserve NUMERIC,
    lp_token1_out_period_sum_pct_reserve NUMERIC,
    swap_token1_in_max BIGINT,
    swap_token1_in_max_t0_complement BIGINT,
    swap_token1_out_max BIGINT,
    swap_token1_out_max_t0_complement BIGINT,
    swap_token0_in_max BIGINT,
    swap_token0_out_max BIGINT,
    swap_token0_in_avg NUMERIC,
    swap_token0_out_avg NUMERIC,
    swap_token1_in_avg NUMERIC,
    swap_token1_out_avg NUMERIC,
    swap_token1_in_max_pct_reserve NUMERIC,
    swap_token1_out_max_pct_reserve NUMERIC,
    swap_token1_in_max_impact_bps NUMERIC,
    swap_token1_out_max_impact_bps NUMERIC,
    swap_token0_in_max_impact_bps NUMERIC,
    swap_token0_out_max_impact_bps NUMERIC,
    swap_token0_in_avg_impact_bps NUMERIC,
    swap_token0_out_avg_impact_bps NUMERIC,
    swap_token1_in_avg_impact_bps NUMERIC,
    swap_token1_out_avg_impact_bps NUMERIC,
    vwap_buy_t0_avg NUMERIC,
    vwap_sell_t0_avg NUMERIC,
    price_t1_per_t0_avg NUMERIC,
    spread_vwap_avg_bps NUMERIC,
    price_t1_per_t0_max NUMERIC,
    price_t1_per_t0_min NUMERIC,
    price_t1_per_t0_std NUMERIC,
    swap_vol_t1_total_24h BIGINT,
    swap_vol_t1_total_24h_pct_tvl_in_t1 NUMERIC,
    swap_count_24h BIGINT,
    max_1h_t0_sell_pressure_pct_reserve NUMERIC,
    max_1h_t0_sell_pressure_start TIMESTAMPTZ,
    max_1h_t0_sell_pressure_in_period BIGINT,
    max_1h_t0_sell_pressure_in_period_impact_bps NUMERIC,
    max_1h_t0_buy_pressure_in_period BIGINT,
    max_1h_t0_buy_pressure_in_period_impact_bps NUMERIC
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ml.pool_address,
        ml.protocol,
        ml.token_pair,
        ml.symbols_t0_t1,
        ml.liq_query_id,
        ml.price_t1_per_t0,
        ml.impact_t0_quantities,
        ml.impact_from_t0_sell1_bps,
        ml.impact_from_t0_sell2_bps,
        ml.impact_from_t0_sell3_bps,
        ml.t0_reserve,
        ml.t1_reserve,
        ml.tvl_in_t1_units,
        ml.reserve_t0_t1_millions,
        ml.reserve_t0_t1_balance_pct,
        ml.swap_count_period,
        ml.lp_in_count_period,
        ml.lp_out_count_period,
        ml.swap_vol_in_t1_units,
        ml.swap_vol_in_t0_units,
        ml.swap_vol_in_t1_units_pct_reserve,
        ml.swap_vol_in_t0_units_pct_reserve,
        ml.swap_vol_out_t1_units,
        ml.swap_vol_out_t0_units,
        ml.swap_vol_out_t1_units_pct_reserve,
        ml.swap_vol_out_t0_units_pct_reserve,
        ml.swap_vol_period_t0_in,
        ml.swap_vol_period_t0_out,
        ml.swap_vol_period_t1_in,
        ml.swap_vol_period_t1_out,
        ml.lp_token0_in_period_sum,
        ml.lp_token0_out_period_sum,
        ml.lp_token1_in_period_sum,
        ml.lp_token1_out_period_sum,
        ml.lp_token0_in_period_sum_pct_reserve,
        ml.lp_token0_out_period_sum_pct_reserve,
        ml.lp_token1_in_period_sum_pct_reserve,
        ml.lp_token1_out_period_sum_pct_reserve,
        ml.swap_token1_in_max,
        ml.swap_token1_in_max_t0_complement,
        ml.swap_token1_out_max,
        ml.swap_token1_out_max_t0_complement,
        ml.swap_token0_in_max,
        ml.swap_token0_out_max,
        ml.swap_token0_in_avg,
        ml.swap_token0_out_avg,
        ml.swap_token1_in_avg,
        ml.swap_token1_out_avg,
        ml.swap_token1_in_max_pct_reserve,
        ml.swap_token1_out_max_pct_reserve,
        ml.swap_token1_in_max_impact_bps,
        ml.swap_token1_out_max_impact_bps,
        ml.swap_token0_in_max_impact_bps,
        ml.swap_token0_out_max_impact_bps,
        ml.swap_token0_in_avg_impact_bps,
        ml.swap_token0_out_avg_impact_bps,
        ml.swap_token1_in_avg_impact_bps,
        ml.swap_token1_out_avg_impact_bps,
        ml.vwap_buy_t0_avg,
        ml.vwap_sell_t0_avg,
        ml.price_t1_per_t0_avg,
        ml.spread_vwap_avg_bps,
        ml.price_t1_per_t0_max,
        ml.price_t1_per_t0_min,
        ml.price_t1_per_t0_std,
        ml.swap_vol_t1_total_24h,
        ml.swap_vol_t1_total_24h_pct_tvl_in_t1,
        ml.swap_count_24h,
        ml.max_1h_t0_sell_pressure_pct_reserve,
        ml.max_1h_t0_sell_pressure_start,
        ml.max_1h_t0_sell_pressure_in_period,
        ml.max_1h_t0_sell_pressure_in_period_impact_bps,
        ml.max_1h_t0_buy_pressure_in_period,
        ml.max_1h_t0_buy_pressure_in_period_impact_bps
    FROM dexes.mat_dex_last ml
    WHERE ml.protocol = protocol_param
      AND ml.token_pair = pair_param;
END;
$$;
