from __future__ import annotations

from app.pages.common import PageAction, PageConfig, WidgetConfig


PAGE_CONFIG = PageConfig(
    slug="kamino",
    label="Kamino Lend",
    api_page_id="kamino",
    show_protocol_pair_filters=False,
    page_actions=[
        PageAction("kamino-explainer", "Protocol Explainer", icon="book", modal_kind="html"),
        PageAction("kamino-market-assets", "Market Assets", icon="grid", modal_kind="table", endpoint="kamino-market-assets"),
        PageAction("kamino-market-terms", "Market Terms", icon="settings", modal_kind="table", endpoint="kamino-config-table"),
    ],
    widgets=[
        # Group 1: Core KPIs (2-col, 4 rows)
        WidgetConfig("kpi-utilization-by-reserve", "Utilization Factor by Reserve", "kpi", "panel panel-kpi kamino-slot-kpi-a1",
                     tooltip="The current ratio of borrow assets outstanding vs. total assets supplied. This variable determines supply and borrow APYs and is also a key indicator of available liquidity for withdrawals."),
        WidgetConfig("kpi-loan-value", "Loan Value Outstanding", "kpi", "panel panel-kpi kamino-slot-kpi-b1",
                     tooltip="The total value of debt outstanding across all obligations and all tokens, valued in market quote currency."),
        WidgetConfig("kpi-obligations-debt-size", "Number of Obligations with Debt and Avg.Size", "kpi", "panel panel-kpi kamino-slot-kpi-a2",
                     tooltip="Count of obligations with non-negligible debt and the average debt value held by them."),
        WidgetConfig("kpi-share-borrow-asset", "Share by Borrow Asset", "kpi", "panel panel-kpi kamino-slot-kpi-b2",
                     tooltip="Share of total outstanding debt represented by each borrow asset in this market."),
        WidgetConfig("kpi-ltv-hf", "Avg. Current Loan LTV / HF", "kpi", "panel panel-kpi kamino-slot-kpi-a3",
                     tooltip="Average LTV and Health Factor (HF) weighted by market value of debt for obligations with debt value \u2265 1 (in market currency). Positions become liquidatable when HF = 1. The health factor is the ratio of the unhealthy borrow limit (based on collateral composition and liquidation thresholds) divided by the borrow-factor-adjusted market value of debt."),
        WidgetConfig("kpi-collateral-value", "Collateral Deposited", "kpi", "panel panel-kpi kamino-slot-kpi-b3",
                     tooltip="The total value of collateral deposited across all obligations and all tokens, valued in market quote currency."),
        WidgetConfig("kpi-unhealthy-share", "Unhealthy Loans as Share of Total", "kpi", "panel panel-kpi kamino-slot-kpi-a4",
                     tooltip="Share of total outstanding debt value currently marked as unhealthy."),
        WidgetConfig("kpi-share-collateral-asset", "Share by Collateral Asset", "kpi", "panel panel-kpi kamino-slot-kpi-b4",
                     tooltip="Share of total collateral value represented by each collateral asset accepted in this market."),
        # Group 2: Zero-use + APY KPIs (2-col, 2 rows)
        WidgetConfig("kpi-zero-use-count", "Zero-Use Accounts", "kpi", "panel panel-kpi kamino-slot-kpi-a5",
                     tooltip="The number of accounts with deposits only and no outstanding loans."),
        WidgetConfig("kpi-zero-use-capacity", "Zero-Use Capacity", "kpi", "panel panel-kpi kamino-slot-kpi-b5",
                     tooltip="The total borrowing capacity available to deposit-only accounts."),
        WidgetConfig("kpi-borrow-apy", "Current Borrow APY by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-a6",
                     tooltip="The core APY excluding any additional rewards or incentive programs."),
        WidgetConfig("kpi-supply-apy", "Current Supply APY by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-b6",
                     tooltip="The core APY excluding any additional rewards or incentive programs."),
        # Group 3: Activity KPIs (2-col, 4 rows)
        WidgetConfig("kpi-borrow-vol-24h", "24h Borrow Volume by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-a7"),
        WidgetConfig("kpi-repay-vol-24h", "24h Repay Volume by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-b7"),
        WidgetConfig("kpi-liquidation-vol-30d", "30d Liquidation Volume", "kpi", "panel panel-kpi kamino-slot-kpi-a8"),
        WidgetConfig("kpi-liquidation-count-30d", "30d Liquidations Count", "kpi", "panel panel-kpi kamino-slot-kpi-b8"),
        WidgetConfig("kpi-withdraw-vol-24h", "24hr Withdraw Volume by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-a9"),
        WidgetConfig("kpi-deposit-vol-24h", "24hr Deposit Volume by Asset", "kpi", "panel panel-kpi kamino-slot-kpi-b9"),
        WidgetConfig("kpi-liquidation-avg-size", "Average Liquidation Size", "kpi", "panel panel-kpi kamino-slot-kpi-a10"),
        WidgetConfig("kpi-days-no-liquidation", "Days without Liquidations", "kpi", "panel panel-kpi kamino-slot-kpi-b10"),
        # Charts (2-col layout)
        WidgetConfig("kamino-supply-collateral-status", "Collateral and Borrow Asset Balances & Status", "chart", "panel panel-large kamino-slot-col-left-top",
                     tooltip="Total collateral and borrow assets tied to this market across all tokens, valued in market currency and broken down by economic, health, and risk status."),
        WidgetConfig("kamino-rate-curve", "Borrow Rate Curve", "chart", "panel panel-large kamino-slot-col-left-mid",
                     tooltip="Visualizes the protocol\u2019s APY pricing curve and where the utilization of each asset currently lies."),
        WidgetConfig("kamino-loan-size-dist", "Loan Size Distribution & Health Factors", "chart", "panel panel-large kamino-slot-col-left-mid2",
                     tooltip="Visualises the ranked distribution of obligation debt at market currency value, and HF associated with each one."),
        WidgetConfig("kamino-stress-debt", "Stress Test: Total Debt At-Risk", "chart", "panel panel-large kamino-slot-col-left-mid3", detail_table_id="kamino-sensitivity-table",
                     tooltip="Examines how much the value of liabilities would need to rise, or collateral would need to fall, before debt becomes unhealthy. The fraction of debt that becomes liquidatable is highlighted. If health factors are closer to 1, slopes draw inward. Vertical green dotted lines show 1st and 2nd standard deviations of underlying token price; if these intersect the slopes, ordinary volatility implies plausible liquidation risk."),
        WidgetConfig("kamino-utilization-timeseries", "Utilization (timeseries)", "chart", "panel panel-large kamino-slot-col-right-top",
                     tooltip="Time series of all borrow assets supplied and borrowed over time, alongside utilization."),
        WidgetConfig("kamino-ltv-hf-timeseries", "Obligations: Debt-Weighted HF & LTV", "chart", "panel panel-large kamino-slot-col-right-mid",
                     tooltip="Shows median and weighted average LTVs, and weighted average HF over time for obligations with debt value \u2265 1."),
        WidgetConfig("kamino-liability-flows", "Loan Market Borrow Asset Flows by Type", "chart", "panel panel-large kamino-slot-col-right-mid2",
                     tooltip="Monitors all token flows for market reserves, including both borrow and collateral activity."),
        WidgetConfig("kamino-liquidations", "Liquidations of Borrow Asset Positions", "chart", "panel panel-large kamino-slot-col-right-bottom",
                     tooltip="Monitors all liquidations across the market. Under normal conditions, this chart is expected to show little to no activity."),
        WidgetConfig("kamino-obligation-watchlist", "Market Obligations Watchlist", "table", "panel panel-wide-table kamino-slot-bottom", expandable=False),
    ],
)
